blank_issues_enabled: true
contact_links:
  - name: Our forum ğŸ’¬
    url: https://forum.openwrt.org/
    about: Ask and answer questions here.
  - name: Our website ğŸŒğŸ”—
    url: https://openwrt.org/
    about: The main website.
  - name: Table of hardware ğŸ’»âš™ï¸
    url: https://openwrt.org/toh/start
    about: Find your hardware platform here.
  - name: JS API docs ğŸ“â™¨ï¸
    url: https://openwrt.github.io/luci/jsapi/
